### ISSUE TITLE
potentially incorrect example for time?

### ISSUE THREAD

**Issue by Disputes** [doggiekuk/Sniper-#2]
havnt been able to compile yet but i assume the t.tm is for the drop time. i checked the documentation and it said t.tm_mon was 0-11 with 0 being jan and 11 being dec if this is correct then would the example be wrong and it says it is translated to 11/5/2017 not 12/5/2017

![image](https://user-images.githubusercontent.com/19439141/28064699-93caea30-662d-11e7-9692-7c7332c46bfe.png)
seems like its not finding the other libs too but thats probs a error on my end

**Comment by doggiekuk** [comment]
Thanks for noting. Will update the documentation.

Libraries missing are on your end and you'll need to install them 👍
